---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: echo
  args: ["I am building!!!!"]

# Describe the inputs to this Task
inputs:
- name: hello-java-code
