---
# Declare the resources that will be used in the pipeline
# Each resource has a name
resources:
- name: src
  type: git
  source:
    uri: https://github.com/monodot/hello-java
    branch: master

# Jobs comprise a series of Tasks
# e.g. "build-app" -> "build", "create-image", etc.
jobs:

# This test job will use the source code from GitHub,
# Then execute the 'test' task which is defined in the repo.
- name: unit-test
  plan:
  - get: src
    trigger: true # Trigger this job whenever 'hello-java-code' has a new version (i.e. a new Git commit)
  - task: run-unit-tests
    file: hello-java-code/ci/concourse/unit-test.yml

# This build job will use the source code from GitHub,
# Then execute a 'build' task which is defined in the repo.
- name: package
  plan:
  - get: src
    trigger: true
    passed:
    - unit-test  # The 'unit-test' job must have passed for this job to execute
  - task: build
    file: hello-java-code/ci/concourse/package.yml
